[project]
name = "openbb-charting"
version = "2.3.4"
description = "Charting extension for OpenBB"
authors = [
    {name = "OpenBB Team", email = "hello@openbb.co"},
]
license = {text = "AGPL-3.0-only"}
readme = "README.md"
requires-python = ">=3.9.21,<3.13"
dependencies = [
    "openbb-core",
    "pandas-ta-openbb>=0.4.20,<0.5.0",
    "plotly>=5.24.1,<6.0.0",
    "nbformat>=5.10.0,<6.0.0",
]

[project.optional-dependencies]
optional = [
    "pywry>=0.6.2,<0.7.0",
]

[project.entry-points.openbb_obbject_extension]
openbb_charting = "openbb_charting:ext"

[tool.uv.sources]
openbb-core = { path = "../../core", editable = true }

[tool.hatch.build.targets.wheel]
packages = ["openbb_charting"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
