[project]
name = "openbb-cboe"
version = "1.4.1"
description = "CBOE extension for OpenBB"
authors = [
    {name = "OpenBB Team", email = "hello@openbb.co"},
]
license = {text = "AGPL-3.0-only"}
readme = "README.md"
requires-python = ">=3.9.21,<3.13"
dependencies = [
    "aiohttp-client-cache>=0.11.0,<0.12.0",
    "aiosqlite>=0.20.0,<0.21.0",
    "openbb-core",
]

[project.entry-points.openbb_provider_extension]
cboe = "openbb_cboe:cboe_provider"

[tool.uv.sources]
openbb-core = { path = "../../core", editable = true }

[tool.hatch.build.targets.wheel]
packages = ["openbb_cboe"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
