[project]
name = "openbb-nasdaq"
version = "1.4.1"
description = "Nasdaq extension for OpenBB"
authors = [
    {name = "OpenBB Team", email = "hello@openbb.co"},
]
license = {text = "AGPL-3.0-only"}
readme = "README.md"
requires-python = ">=3.9.21,<3.13"
dependencies = [
    "openbb-core",
    "random-user-agent>=1.0.1,<2.0.0",
    "nasdaq-data-link>=1.0.4,<2.0.0",
]

[project.entry-points.openbb_provider_extension]
nasdaq = "openbb_nasdaq:nasdaq_provider"

[tool.uv.sources]
openbb-core = { path = "../../core", editable = true }

[tool.hatch.build.targets.wheel]
packages = ["openbb_nasdaq"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
