[project]
name = "openbb-equity"
version = "1.4.1"
description = "Equity extension for OpenBB"
authors = [
    {name = "OpenBB Team", email = "hello@openbb.co"},
]
license = {text = "AGPL-3.0-only"}
readme = "README.md"
requires-python = ">=3.9.21,<3.13"
dependencies = [
    "openbb-core",
]

[project.entry-points.openbb_core_extension]
equity = "openbb_equity.equity_router:router"

[project.entry-points.openbb_charting_extension]
equity = "openbb_equity.equity_views:EquityViews"

[tool.uv.sources]
openbb-core = { path = "../../core", editable = true }

[tool.hatch.build.targets.wheel]
packages = ["openbb_equity"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
