[project]
name = "peppermint-stock"
version = "0.1.0"
description = "stock app"
authors = [
    {name = "Peter Cai",email = "petercaica@hotmail.com"}
]
readme = "README.md"
requires-python = ">=3.12,<3.13"
packages = [
    { include = "openbb_platform"}
    ]

dependencies = [
    "numpy (==2.2.4)",
    "pandas (==2.2.3)",
    "py-mini-racer (==0.6.0)",
    "mini-racer (==0.12.4)",
    "arrow (==1.3.0)",
    "bokeh (==3.6.2)",
    "pymysql (==1.1.1)",
    "requests (==2.32.3)",
    "logbook (==1.8.1)",
    "sqlalchemy (==2.0.40)",
    "tornado (==6.4.2)",
    "tqdm (==4.67.1)",
    "easytrader (==0.23.3)",
    "beautifulsoup4 (==4.13.3)",
    "pycryptodome (==3.22.0)",
    "python-dateutil (==2.9.0.post0)",
    "ta-lib @ file:./pkg/ta_lib-0.6.3-cp312-cp312-win_amd64.whl",
    "openbb @ file:./openbb_platform"
]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
