[project]
name = "openbb-multpl"
version = "1.1.1"
description = "Public data on historical S&P Multiples."
authors = [
    {name = "OpenBB Team", email = "hello@openbb.co"},
]
readme = "README.md"
requires-python = ">=3.9.21,<3.13"
dependencies = [
    "openbb-core",
]

[project.entry-points.openbb_provider_extension]
multpl = "openbb_multpl:multpl_provider"

[tool.uv.sources]
openbb-core = { path = "../../core", editable = true }

[tool.hatch.build.targets.wheel]
packages = ["openbb_multpl"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
