[project]
name = "openbb-yfinance"
version = "1.4.6"
description = "yfinance extension for OpenBB"
authors = [
    {name = "OpenBB Team", email = "hello@openbb.co"},
]
license = {text = "AGPL-3.0-only"}
readme = "README.md"
requires-python = ">=3.9.21,<3.13"
dependencies = [
    "yfinance==0.2.58",
    "openbb-core",
    "curl-adapter>=1.0.0.post3,<2.0.0",
]

[project.entry-points.openbb_provider_extension]
yfinance = "openbb_yfinance:yfinance_provider"

[tool.uv.sources]
openbb-core = { path = "../../core", editable = true }

[tool.hatch.build.targets.wheel]
packages = ["openbb_yfinance"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
