[project]
name = "openbb-index"
version = "1.4.1"
description = "Index extension for OpenBB"
authors = [
    {name = "OpenBB Team", email = "hello@openbb.co"},
]
license = {text = "AGPL-3.0-only"}
readme = "README.md"
requires-python = ">=3.9.21,<3.13"
dependencies = [
    "openbb-core",
]

[project.entry-points.openbb_core_extension]
index = "openbb_index.index_router:router"

[project.entry-points.openbb_charting_extension]
index = "openbb_index.index_views:IndexViews"

[tool.uv.sources]
openbb-core = { path = "../../core", editable = true }

[tool.hatch.build.targets.wheel]
packages = ["openbb_index"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
