[project]
name = "openbb-imf"
version = "1.1.1"
description = "https://datahelp.imf.org/knowledgebase/articles/630877-api"
authors = [
    {name = "OpenBB Team", email = "hello@openbb.co"},
]
license = {text = "AGPL-3.0-only"}
readme = "README.md"
requires-python = ">=3.9.21,<3.13"
dependencies = [
    "openbb-core",
]

[project.entry-points.openbb_provider_extension]
imf = "openbb_imf:imf_provider"

[tool.uv.sources]
openbb-core = { path = "../../core", editable = true }

[tool.hatch.build.targets.wheel]
packages = ["openbb_imf"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
