[project]
name = "openbb-economy"
version = "1.4.2"
description = "Economy extension for OpenBB"
authors = [
    {name = "OpenBB Team", email = "hello@openbb.co"},
]
license = {text = "AGPL-3.0-only"}
readme = "README.md"
requires-python = ">=3.9.21,<3.13"
dependencies = [
    "openbb-core",
]

[project.entry-points.openbb_core_extension]
economy = "openbb_economy.economy_router:router"

[project.entry-points.openbb_charting_extension]
economy = "openbb_economy.economy_views:EconomyViews"

[tool.uv.sources]
openbb-core = { path = "../../core", editable = true }

[tool.hatch.build.targets.wheel]
packages = ["openbb_economy"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
