[project]
name = "openbb-currency"
version = "1.4.1"
description = "Currency extension for OpenBB"
authors = [
    {name = "OpenBB Team", email = "hello@openbb.co"},
]
license = {text = "AGPL-3.0-only"}
readme = "README.md"
requires-python = ">=3.9.21,<3.13"
dependencies = [
    "openbb-core",
]

[project.entry-points.openbb_core_extension]
currency = "openbb_currency.currency_router:router"

[project.entry-points.openbb_charting_extension]
currency = "openbb_currency.currency_views:CurrencyViews"

[tool.uv.sources]
openbb-core = { path = "../../core", editable = true }

[tool.hatch.build.targets.wheel]
packages = ["openbb_currency"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
