[project]
name = "openbb-sec"
version = "1.4.3"
description = "SEC extension for OpenBB"
authors = [
    {name = "OpenBB Team", email = "hello@openbb.co"},
]
license = {text = "AGPL-3.0-only"}
readme = "README.md"
requires-python = ">=3.9.21,<3.13"
dependencies = [
    "openbb-core",
    "aiohttp-client-cache>=0.11.0,<0.12.0",
    "aiosqlite>=0.20.0,<0.21.0",
    "xmltodict>=0.13.0,<0.14.0",
    "beautifulsoup4>=4.12,<5.0",
    "lxml>=5.2.1,<6.0.0",
    "trafilatura>=2.0,<3.0",
    "inscriptis>=2.5.3,<3.0.0",
]

[project.entry-points.openbb_provider_extension]
sec = "openbb_sec:sec_provider"

[tool.uv.sources]
openbb-core = { path = "../../core", editable = true }

[tool.hatch.build.targets.wheel]
packages = ["openbb_sec"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
