[project]
name = "openbb"
version = "4.4.4"
description = "Investment research for everyone, anywhere."
authors = [
    {name = "OpenBB Team", email = "hello@openbb.co"},
]
license = {text = "AGPL-3.0-only"}
readme = "README.md"
requires-python = ">=3.9.21,<3.13"
dependencies = [
    "openbb-core",
    "openbb-platform-api",

    "openbb-benzinga",
    "openbb-bls",
    "openbb-cftc",
    "openbb-econdb",
    "openbb-federal-reserve",
    "openbb-fmp",
    "openbb-fred",
    "openbb-imf",
    "openbb-intrinio",
    "openbb-oecd",
    "openbb-polygon",
    "openbb-sec",
    "openbb-tiingo",
    "openbb-tradingeconomics",
    "openbb-us-eia",
    "openbb-yfinance",

    "openbb-commodity",
    "openbb-crypto",
    "openbb-currency",
    "openbb-derivatives",
    "openbb-economy",
    "openbb-equity",
    "openbb-etf",
    "openbb-fixedincome",
    "openbb-index",
    "openbb-news",
    "openbb-regulators",
]

[project.optional-dependencies]
alpha_vantage = ["openbb-alpha-vantage"]
biztoc = ["openbb-biztoc"]
cboe = ["openbb-cboe"]
charting = ["openbb-charting"]
ecb = ["openbb-ecb"]
econometrics = ["openbb-econometrics"]
finra = ["openbb-finra"]
finviz = ["openbb-finviz"]
government_us = ["openbb-government-us"]
nasdaq = ["openbb-nasdaq"]
multpl = ["openbb-multpl"]
quantitative = ["openbb-quantitative"]
seeking_alpha = ["openbb-seeking-alpha"]
stockgrid = ["openbb-stockgrid"]
technical = ["openbb-technical"]
tmx = ["openbb-tmx"]
tradier = ["openbb-tradier"]
wsj = ["openbb-wsj"]

all = [
    "openbb-alpha-vantage",
    "openbb-biztoc",
    "openbb-cboe",
    "openbb-charting",
    "openbb-deribit",
    "openbb-ecb",
    "openbb-econometrics",
    "openbb-finra",
    "openbb-finviz",
    "openbb-government-us",
    "openbb-multpl",
    "openbb-nasdaq",
    "openbb-quantitative",
    "openbb-seeking-alpha",
    "openbb-stockgrid",
    "openbb-technical",
    "openbb-tmx",
    "openbb-tradier",
    "openbb-wsj",
]

[tool.uv.sources]
openbb-core = {workspace = true}
openbb-platform-api = {workspace = true}
openbb-benzinga = {workspace = true}
openbb-bls = {workspace = true}
openbb-cftc = {workspace = true}
openbb-econdb = {workspace = true}
openbb-federal-reserve = {workspace = true}
openbb-fmp = {workspace = true}
openbb-fred = {workspace = true}
openbb-imf = {workspace = true}
openbb-intrinio = {workspace = true}
openbb-oecd = {workspace = true}
openbb-polygon = {workspace = true}
openbb-sec = {workspace = true}
openbb-tiingo = {workspace = true}
openbb-tradingeconomics = {workspace = true}
openbb-us-eia = {workspace = true}
openbb-yfinance = {workspace = true}
openbb-commodity = {workspace = true}
openbb-crypto = {workspace = true}
openbb-currency = {workspace = true}
openbb-derivatives = {workspace = true}
openbb-economy = {workspace = true}
openbb-equity = {workspace = true}
openbb-etf = {workspace = true}
openbb-fixedincome = {workspace = true}
openbb-index = {workspace = true}
openbb-news = {workspace = true}
openbb-regulators = {workspace = true}
openbb-alpha-vantage = {workspace = true}
openbb-biztoc = {workspace = true}
openbb-cboe = {workspace = true}
openbb-deribit = {workspace = true}
openbb-ecb = {workspace = true}
openbb-finra = {workspace = true}
openbb-finviz = {workspace = true}
openbb-government-us = {workspace = true}
openbb-multpl = {workspace = true}
openbb-nasdaq = {workspace = true}
openbb-seeking-alpha = {workspace = true}
openbb-stockgrid = {workspace = true}
openbb-tmx = {workspace = true}
openbb-tradier = {workspace = true}
openbb-wsj = {workspace = true}
openbb-charting = {workspace = true}
openbb-econometrics = {workspace = true}
openbb-quantitative = {workspace = true}
openbb-technical = {workspace = true}

[tool.hatch.build.targets.wheel]
packages = ["openbb"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
